name: Code quality

on:
  - push
  - pull_request

env:
  SOURCE_DIR: kvac
  TEST_DIR: tests

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: pylint
      run: |
        pylint $SOURCE_DIR $TEST_DIR
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install -r requirements.txt
    - name: mypy
      run: |
        mypy $SOURCE_DIR $TEST_DIR
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: pytest
      run: |
        python -m pytest $TEST_DIR
